/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdsenseRouteImport } from './routes/adsense'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as CoursesRouteImport } from './routes/courses'
import { Route as LessonsRouteImport } from './routes/lessons'
import { Route as PracticeRouteImport } from './routes/practice'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as UploadsRouteImport } from './routes/uploads'
import { Route as CoursesSlugRouteImport } from './routes/courses_.$slug'
import { Route as LessonsIdRouteImport } from './routes/lessons_.$id'
import { Route as PracticeIdRouteImport } from './routes/practice_.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdsenseRoute = AdsenseRouteImport.update({
  id: '/adsense',
  path: '/adsense',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesRoute = CoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonsRoute = LessonsRouteImport.update({
  id: '/lessons',
  path: '/lessons',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeRoute = PracticeRouteImport.update({
  id: '/practice',
  path: '/practice',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const UploadsRoute = UploadsRouteImport.update({
  id: '/uploads',
  path: '/uploads',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesSlugRoute = CoursesSlugRouteImport.update({
  id: '/courses_/$slug',
  path: '/courses/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonsIdRoute = LessonsIdRouteImport.update({
  id: '/lessons_/$id',
  path: '/lessons/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeIdRoute = PracticeIdRouteImport.update({
  id: '/practice_/$id',
  path: '/practice/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/adsense': typeof AdsenseRoute
  '/alerts': typeof AlertsRoute
  '/courses': typeof CoursesRoute
  '/lessons': typeof LessonsRoute
  '/practice': typeof PracticeRoute
  '/saved': typeof SavedRoute
  '/uploads': typeof UploadsRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/lessons/$id': typeof LessonsIdRoute
  '/practice/$id': typeof PracticeIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/adsense': typeof AdsenseRoute
  '/alerts': typeof AlertsRoute
  '/courses': typeof CoursesRoute
  '/lessons': typeof LessonsRoute
  '/practice': typeof PracticeRoute
  '/saved': typeof SavedRoute
  '/uploads': typeof UploadsRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/lessons/$id': typeof LessonsIdRoute
  '/practice/$id': typeof PracticeIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/adsense': typeof AdsenseRoute
  '/alerts': typeof AlertsRoute
  '/courses': typeof CoursesRoute
  '/lessons': typeof LessonsRoute
  '/practice': typeof PracticeRoute
  '/saved': typeof SavedRoute
  '/uploads': typeof UploadsRoute
  '/courses_/$slug': typeof CoursesSlugRoute
  '/lessons_/$id': typeof LessonsIdRoute
  '/practice_/$id': typeof PracticeIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/adsense'
    | '/alerts'
    | '/courses'
    | '/lessons'
    | '/practice'
    | '/saved'
    | '/uploads'
    | '/courses/$slug'
    | '/lessons/$id'
    | '/practice/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/adsense'
    | '/alerts'
    | '/courses'
    | '/lessons'
    | '/practice'
    | '/saved'
    | '/uploads'
    | '/courses/$slug'
    | '/lessons/$id'
    | '/practice/$id'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/adsense'
    | '/alerts'
    | '/courses'
    | '/lessons'
    | '/practice'
    | '/saved'
    | '/uploads'
    | '/courses_/$slug'
    | '/lessons_/$id'
    | '/practice_/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdsenseRoute: typeof AdsenseRoute
  AlertsRoute: typeof AlertsRoute
  CoursesRoute: typeof CoursesRoute
  LessonsRoute: typeof LessonsRoute
  PracticeRoute: typeof PracticeRoute
  SavedRoute: typeof SavedRoute
  UploadsRoute: typeof UploadsRoute
  CoursesSlugRoute: typeof CoursesSlugRoute
  LessonsIdRoute: typeof LessonsIdRoute
  PracticeIdRoute: typeof PracticeIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adsense': {
      id: '/adsense'
      path: '/adsense'
      fullPath: '/adsense'
      preLoaderRoute: typeof AdsenseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lessons': {
      id: '/lessons'
      path: '/lessons'
      fullPath: '/lessons'
      preLoaderRoute: typeof LessonsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice': {
      id: '/practice'
      path: '/practice'
      fullPath: '/practice'
      preLoaderRoute: typeof PracticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/uploads': {
      id: '/uploads'
      path: '/uploads'
      fullPath: '/uploads'
      preLoaderRoute: typeof UploadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses_/$slug': {
      id: '/courses_/$slug'
      path: '/courses/$slug'
      fullPath: '/courses/$slug'
      preLoaderRoute: typeof CoursesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lessons_/$id': {
      id: '/lessons_/$id'
      path: '/lessons/$id'
      fullPath: '/lessons/$id'
      preLoaderRoute: typeof LessonsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice_/$id': {
      id: '/practice_/$id'
      path: '/practice/$id'
      fullPath: '/practice/$id'
      preLoaderRoute: typeof PracticeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdsenseRoute: AdsenseRoute,
  AlertsRoute: AlertsRoute,
  CoursesRoute: CoursesRoute,
  LessonsRoute: LessonsRoute,
  PracticeRoute: PracticeRoute,
  SavedRoute: SavedRoute,
  UploadsRoute: UploadsRoute,
  CoursesSlugRoute: CoursesSlugRoute,
  LessonsIdRoute: LessonsIdRoute,
  PracticeIdRoute: PracticeIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
